- examples/full.ps1
- src/Private/Helpers.ps1
- src/Public/Elements.ps1
- src/Public/Outputs.ps1
- src/Public/Pages.ps1
- src/Public/Utilities.ps1
- src/Templates/Public/scripts/default.js
- src/Templates/Public/styles/default-dark.css
- src/Templates/Public/styles/default-terminal.css
- src/Templates/Public/styles/default.css
- src/Templates/Views/elements/form.pode
- src/Templates/Views/elements/select.pode
- src/Templates/Views/elements/table.pode
- src/Templates/Views/index.pode
- src/Templates/Views/layouts/modal.pode
- src/Templates/Views/layouts/steps.pode
- src/Templates/Views/login.pode
- src/Templates/Views/shared/head.pode
Bulk of this improves the way themes work, adding a new Auto theme to switch between light/dark based on a user's system theme, and allows save/toggling theme via Auth data and cookie.
Resolves #13
> Enables toggling of theme, adds new Auto theme, plus extras

- examples/endpoints.ps1
- src/Private/Helpers.ps1
- src/Public/Elements.ps1
- src/Public/Layouts.ps1
- src/Public/Pages.ps1
- src/Public/Utilities.ps1
Adds -EndpointName support on `Use-PodeWebTemplates`, and to relevant Pages, Elements and Layouts.
Resolves #18
> Adds EndpointName support

- examples/upload.ps1
- src/Templates/Public/scripts/default.js
Fixes uploading a file via a form file input element.
Resolves #15
> Fix for file uploads

- .build.ps1
- .github/workflows/ci.yml
- .gitignore
- README.md
- examples/server.psd1
- package.json
- src/Templates/Public/scripts/default.js
- src/Templates/Views/shared/head.pode
- src/Templates/Views/shared/scripts.pode
Bundle the libraries with Pode.Web, and move away from using CDN versions - this will allow Pode.Web to be used in offline environments.
Resolves #29
> Bundle frontend libraries with module

- docs/Tutorials/Elements/Button.md
- docs/Tutorials/Elements/Link.md
- docs/Tutorials/Outputs/Page.md
- docs/Tutorials/Outputs/URL.md
- docs/Tutorials/Pages.md
- examples/full.ps1
- src/Public/Elements.ps1
- src/Public/Navigation.ps1
- src/Public/Outputs.ps1
- src/Public/Pages.ps1
- src/Templates/Public/scripts/default.js
- src/Templates/Public/styles/default.css
- src/Templates/Views/elements/button.pode
- src/Templates/Views/index.pode
- src/Templates/Views/navigation/link.pode
Allows URL redirection to open in a `-NewTab` for links, buttons, pages, navbar links. Also adds a new `Add-PodeWebPageLink` which adds a page link to the sidebar - which can either be a URL or a scriptblock with output actions.
Resolves #71
> Adds -NewTab to Pages, Links, and Buttons, and adds new Add-PodeWebPageLink

- src/Public/Pages.ps1
Fix for building pages from modules with cmdlets and nested functions. This allows Pode.Web to build pages for more modules, such as DBATools.
Resolves #128
> Fix for building pages from modules with cmdlets and nested functions

- examples/steps.ps1
- src/Templates/Public/scripts/default.js
Fixes using File Upload input in Steps and Modals.
Resolves #130
> Fixes for file upload inputs in steps/modals

- src/Private/Helpers.ps1
- src/Public/Pages.ps1
- src/Public/Utilities.ps1
When the Home page redirects, due to not being set/configured, the page it redirects to should be a page with no access restrictions - to prevent 403 pages for non-auth'd users.
Resolves #168
> Make the home page redirect to the first page with no access restrictions

- examples/full.ps1
- src/Public/Elements.ps1
- src/Templates/Public/scripts/default.js
Adds better min/max x/y support for charts, so they can be more easily configured separately.
Changes the way updating a chart works, by calling `.update()` rather than destroying then recreating.
> Update charts rather than full rebuild

- src/Private/Helpers.ps1
- src/Templates/Views/index.pode
Fixes the sorting of pages in the sidebar to be alphabetical.
Resolves #199
> Fix for sorting pages alphabetically

- src/Templates/Public/scripts/default.js
- src/Templates/Views/elements/form.pode
- src/Templates/Views/login.pode
Adds a spinner to the Sign In button on the login page, so the page doesn't look like it's not doing anything sometimes.
Resolves #209
> Fix for login submit missing spinner

- README.md
- docs/Getting-Started/Installation.md
- docs/index.md
- examples/web.config
- src/Private/Helpers.ps1
- src/Public/Elements.ps1
- src/Public/Layouts.ps1
- src/Public/Navigation.ps1
- src/Public/Outputs.ps1
- src/Public/Pages.ps1
- src/Public/Utilities.ps1
- src/Templates/Public/scripts/default.js
- src/Templates/Views/index.pode
- src/Templates/Views/login.pode
- src/Templates/Views/shared/head.pode
- src/Templates/Views/shared/scripts.pode
Enables support for sites created via Pode.Web to be hosted as IIS applications, under other IIS websites.
Resolves #202
> Enable support for hosting as an IIS app

- docs/Tutorials/Elements/Form.md
- docs/Tutorials/Layouts/Steps.md
- examples/steps.ps1
- src/Templates/Public/styles/default.css
Fix a styling issues with `New-PodeWebSteps` when multiple are displayed one after another.
Resolves #215
> Fix Steps styling issue

- src/Templates/Public/scripts/default.js
- src/Templates/Public/styles/default.css
Fix the icon positioning, when used on a table column header.
> Fix icon positioning when in table header

- Dockerfile
- README.md
- alpine.dockerfile
- arm32.dockerfile
- docs/Getting-Started/Installation.md
- docs/Hosting/Docker.md
- examples/Dockerfile
- examples/docker-compose.yml
- examples/full.ps1
Add Dockerfiles for Pode.Web
Resolves #286
> Add pode.web dockerfiles

- examples/full.ps1
- src/Templates/Public/styles/default-terminal.css
- src/Templates/Public/styles/default.css
- src/Templates/Views/index.pode
When a user is logged in, and no AvatarUrl is supplied, then show a default avatar icon (pictured below).
> Show a default avatar for users when logged in

- src/Pode.Web.psm1
- src/Private/Helpers.ps1
- src/Public/Elements.ps1
- src/Templates/Public/scripts/default.js
This contains a few fixes for some minor issues:
* Stop the showing of ANSI colour characters in textboxes from PS7.2+
* An empty home page would at rare times try to redirect to a non-existent login page
* Fix for a table showing a forever loading spinner
* Fix for audio/video text to use better encoding function
> Misc fixes for a few things

- src/Public/Elements.ps1
Fix issue by interpolating string (encoding to HTML) correctly.
#331 
Add any other context or screenshots about the pull request request here.
> Fix bug to properly encode text box value

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/packaging-request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/workflows/ci.yml
- .github/workflows/label-issue-project.yml
- .github/workflows/open-issue-project.yml
- README.md
- docs/roadmap.md
- mkdocs.yml
Adds Issue templates, Project workflows for actions, and Roadmap docs.
> Add issue and workflow templates, and roadmap docs

- .build.ps1
- mkdocs.yml
Bump the versions of MkDocs and the Material Theme.
Resolves #419
> Bump mkdocs and material theme versions

- src/Templates/Public/scripts/default.js
Sets the fill of lines, and tension as well, so they're back to being curved and filled in.
Resolves #423
> Fix line curviness and filling
