src/Public/Components.ps1

If CSV isn't provided PS cannot choose parameter set.
```powershell
New-PodeWebTable -Name 'Results' -Id 'tbl_process_results' -Filter
```

Fix New-PodeWebTable Parameter set not resolved

---

src/Templates/Public/styles/default-dark.css

Before:
After:
* Feel free to fix it in other way.
* The "Terminal" theme have the same problem but I don't know how to fix it to be green color in the CSS.

Can't see Date icon on Dark theme in Chrome 

---

examples/code-editor.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/code-editor.pode

Adds a new `-Value`, `-ReadOnly` and `-Upload` parameters to `New-PodeWebCodeEditor`.
* `-Value` sets a default value for the editor.
* `-ReadOnly` makes the editor read-only.
* `-Upload` is a scriptblock, that shows an upload button above the editor. When click, the language and editor value is posted, and available in the scriptblock as `$WebEvent.Data['language']` and `$WebEvent.Data['value']`
```powershell
$codeEditor = New-PodeWebCodeEditor -Language Html -Name 'Code Editor' -AsCard -Value '<p style="color:white;">well</p>' -Upload {
$WebEvent.Data | Out-Default
}
```

Allows setting of initial value in code editor, and uploading to server

---

src/Private/Helpers.ps1
src/Public/Utilities.ps1
src/Templates/Public/styles/default-light.css
src/Templates/Public/styles/default-terminal.css
src/Templates/Public/styles/default.css
src/Templates/Views/shared/head.pode

Adds support for custom themes. `-Theme` on `Use-PodeWebTemplates` now has a Custom option - the first Custom theme added will be used as the default.
You can also reference custom themes by their name in the pode.web.theme cookie and auth objects.
Resolves #17 
```powershell
Use-PodeWebTemplates -Title Example -Theme Custom
Add-PodeWebCustomTheme -Name Cyborg -Url 'https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/cyborg/bootstrap.min.css'
Add-PodeWebCustomTheme -Name Lux -Url 'https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/lux/bootstrap.min.css'
```

Add support for custom themes

---

src/Templates/Public/scripts/default.js
src/Templates/Views/elements/alert.pode
src/Templates/Views/elements/quote.pode

Fix issue where `Out-PodeWebText` removed alert headers, and didn't decode encoded characters.
Resolves #24

Fix removing alert header, and encoding html

---

src/Private/Helpers.ps1
src/Public/Elements.ps1

Fix an issue with auto-wrapping table/chart output, as `OutputType` is no longer used.
Resolves #27

Fix an issue with auto-wrapping table/chart output

---

src/Public/Elements.ps1

Instead of checking for the ContentLength, check if the Content-Disposition header is on the response for any attachments.
Resolves #30

Check for disposition header instead of content-length

---

src/Templates/Public/scripts/default.js

When an empty array of rows is passed to `Out-PodeWebTable`, just empty the table's body.
Resolves #32

On 0 rows, clear the table's body

---

.gitignore
src/Public/Elements.ps1
src/Public/Pages.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/table.pode

Adds support for have a custom click event, on a table row, via a new `-ClickScriptBlock` on `New-PodeWebTable`. Also lets you hide the back arrow on pages via `-NoBackArrow` on `Add-PodeWebPage` which shows when a page has a query string.
Resolves #28 
For the custom table row click event:
```powershell
Start-PodeServer {
Add-PodeEndpoint -Address localhost -Protocol Http
Use-PodeWebTemplates -Title Tools -Theme Dark
Add-PodeWebPage -Name 'File' -Icon Activity -Layouts @(
New-PodeWebTable -Name 'Explorer' -Id 'DriveExplorer' -AsCard -Click -DataColumn 'Name' -ScriptBlock {
for ($i = 1; $i -lt 4; $i++) {
[PSCustomObject]@{
Name  = "Name$i"
Date  = (Get-Date).ToString()
}
}
} -ClickScriptBlock {
if ($WebEvent.Data.Value -eq 'Name1') {
Sync-PodeWebTable -Id 'DriveExplorer'
}
elseif …
```

Add ClickScriptBlock for table rows, and hide page back arrow

---

examples/multi-table.ps1
src/Private/Helpers.ps1
src/Public/Elements.ps1
src/Public/Layouts.ps1
src/Public/Outputs.ps1
src/Public/Pages.ps1
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Public/styles/default.css
src/Templates/Views/elements/breadcrumb.pode
src/Templates/Views/elements/icon.pode
src/Templates/Views/elements/spinner.pode
src/Templates/Views/index.pode
src/Templates/Views/layouts/modal.pode
src/Templates/Views/shared/_load.pode

The main feature being added is breadcrumbs - these will auto generate for tables, unless a specific breadcrumb has been defined.
To supply a custom breadcrumb, you can use `Set-PodeWebBreadcrumb` with `New-PodeWebBreadcrumbItem`.
Also be added is:
* Support for icons in modal headers
* Support for a title tooltip on icons and spinners
* Support for alignment of table columns, plus icons in column headers, and an override name that should be displayed
* Support on Sync-PodeWebTable and Hide/Show-PodeWebModal to use the `-Name` of the element for ease
* Support for a new "Show-PodeWebError", which will render an alert error box beneath the sending control

Adds breadcrumbs, plus a little more

---

examples/full.ps1
src/Public/Navigation.ps1
src/Public/Pages.ps1
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Public/styles/default-dark.css
src/Templates/Public/styles/default-terminal.css
src/Templates/Public/styles/default.css
src/Templates/Views/index.pode
src/Templates/Views/navigation/divider.pode
src/Templates/Views/navigation/dropdown.pode
src/Templates/Views/navigation/link.pode
src/Templates/Views/shared/_load.pode

Adds in support to add links and dropdowns to the top navigation bar. Links can be URLs, or custom scriptblock's.
Resolves #36 
```powershell
$link1 = New-PodeWebNavLink -Name 'Home' -Url '/' -Icon Home
$link2 = New-PodeWebNavLink -Name 'Dynamic' -Icon Settings -NoAuth -ScriptBlock {
Show-PodeWebToast -Message "I'm from a nav link!"
}
$div1 = New-PodeWebNavDivider
$link3 = New-PodeWebNavLink -Name 'Disabled' -Url '/' -Disabled
$dd1 = New-PodeWebNavDropdown -Name 'Dropdown' -Icon 'maximize-2' -Items @(
New-PodeWebNavLink -Name 'Twitter' -Url 'https://twitter.com'
New-PodeWebNavLink -Name 'Facebook' -Url 'https://facebook.com' -Disabled
New-PodeWebNavDivider
New-PodeWebNavDropdown -Name 'InnerDrop' -Items @(
New-PodeWebNavLink -Name 'Twitch' -Url 'https://twitch.tv'
New-PodeWebNavLink -Name …
```

Adds link and dropdown support to the navbar

---

src/Templates/Public/scripts/default.js

The default.js template file used functions from jQuery that are now deprecated. This fixes those, such as `.on('click'` instead of `.click(`
Resolves #47

Fix deprecated jQuery functions

---

.build.ps1
docs/Getting-Started/Installation.md
mkdocs.yml

Fixes the Basic link on the Getting Started page, and also bumps the mkdocs version.
Resolves #61

Fix Basics link, and bump mkdocs version

---

docs/Tutorials/Pages.md
examples/basic.ps1
examples/pages/services.ps1
src/Public/Pages.ps1

Adds a new `Use-PodeWebPages` function to automatically load page .ps1 files from a /pages folder.
Resolves #48 
Folder structure:
```plain
server.ps1
/pages
page1.ps1
page2.ps1
```
server.ps1:
```powershell
Start-PodeServer {
Add-PodeEndpoint -Address localhost -Port 8090 -Protocol Http
Use-PodeWebTemplates -Title 'Example' -Theme Dark
Use-PodeWebPages
}
```

Add new Use-PodeWebPages functions, to auto-load page files

---

src/Public/Elements.ps1

Allow for either `-Click` or `-ClickScriptBlock` to be supplied to enable clickable rows, not both, on `New-PodeWebTable`.
Resolves #60

Allow for either -Click or -ClickScriptBlock to be supplied

---

src/Public/Layouts.ps1
src/Templates/Views/layouts/grid.pode

This is limited in a grid of 12
This change allows the user to specify a size when creating a New-PodeWebCell in a grid of 12 as bootstrap allows here [bootstrap docs](https://getbootstrap.com/docs/4.0/layout/grid/#all-breakpoints)
```
Start-PodeServer {
Add-PodeEndpoint -Address localhost -Port 8888 -Protocol Http
Use-PodeWebTemplates -Title 'Example' -Theme Light
Add-PodeWebPage -Name 'Services' -NoTitle -Icon 'Settings' -ScriptBlock {
New-PodeWebGrid -Cells @(
New-PodeWebCell -Size 8 -Content @(
New-PodeWebCard -Content @(New-PodeWebParagraph -Value 'Size 8')
)
New-PodeWebCell -Size 4 -Content @(
New-PodeWebCard -Content @(New-PodeWebParagraph -Value 'Size 4')
)
)
}
}
```
Without the change:
With the change:

Added Support for Different Size Cells

---

src/Public/Layouts.ps1
src/Templates/Public/styles/default-light.css
src/Templates/Views/layouts/card.pode

`New-PodeWebCard -NoHide` removes hide button
`New-PodeWebCard -NoTitle` removes the title bar not only the "Name"
There are 2 options I was thinking about, no technical difference of what you can do just what is more clear: 
1. NoTitle = no title bar (removes the bar with the "name" and "hide").
2. Like before NoTitle removes the name so:
NoTitle = no name (remove the name, if you also provide NoHide assumes you also want to remove the bar, but if only no -Name assume you want an empty bar).
It's currently set to option 1.
https://github.com/Badgerati/Pode.Web/issues/72

NoHide on Card optional header

---

docs/Tutorials/Icons.md
docs/Tutorials/Pages.md
src/Public/Pages.ps1
src/Templates/Views/login.pode

The logo on the login page can now be clicked, and redirects back to the login page. This can be changed via `-LogoUrl`.
`-Icon` has also been renamed to `-Logo` on `Set-PodeWebLoginPage`. However, `-Icon` and `-IconUrl` are valid aliases - for now.
(icon was too confusing, and conflicted with other `-Icon` parameters that expect an MDI name)
Resolves #80
By default, it redirects back to the home page. It can be changed using `-LogoUrl`:
```powershell
Set-PodeWebLoginPage -Authentication Example -LogoUrl '<url>'
```

Logo on login page redirects back to home page

---

src/Private/Helpers.ps1
src/Public/Pages.ps1

Adds two new functions: `Get-PodeWebPage` and `Test-PodeWebPage`.
You can either supply no parameters, to get/test all pages. just `-Name` will filter all pages with that name, in every group. `-Group` will filter for pages in specific groups, or to filter for pages in no group use `-NoGroup`.
Resolves #79 
```powershell
Get-PodeWebPage -Name 'Charts'
Get-PodeWebPage -Group 'Tools'
Test-PodeWebPage -Name 'Options' -NoGroup
```

New Get/Test-PodeWebPage functions

---

src/Private/Helpers.ps1
src/Public/Outputs.ps1
src/Public/Pages.ps1
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/index.pode

The default URL path for pages is `/pages/<page>`. This works, until you want two pages with the same name in two different groups; at which point you get a "page already exists" error.
This adds the group name to the URL path when a page has a `-Group` specified: `/groups/<group>/pages/<page>`.
If no group, then the page path is the default.
Resolves #81

Adds the group name to the page URL when a page is grouped

---

src/Templates/Public/styles/default.css
src/Templates/Views/index.pode
src/Templates/Views/login.pode

This is just a quick fix so that <3 emoji in the "powered by" footer is an icon; done so that it renders in all browsers, and doesn't appear as a square.
Also only sets the height of the login logo, rather than height+width, which resulted in squashed logos.

Fix the heart emoji to be an icon

---

docs/Tutorials/Elements/Icon.md
examples/icons.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/icon.pode

Add the following action parameters for `New-PodeWebIcon`: `-Spin`, `-Flip`, and `-Rotate`.
Spin just spins the icon.
Flip can accept either Horizontal or Vertical, and will flip the icon accordingly.
Rotate can accept a value from 45-315 in 45 degree increments.
Resolves #88
```powershell
New-PodeWebIcon -Name 'refresh' -Flip Horizontal
New-PodeWebIcon -Name 'refresh' -Rotate 180
New-PodeWebIcon -Name 'refresh' -Spin
```

Add spin, flip and rotate actions for icons

---

docs/Tutorials/Pages.md
src/Public/Elements.ps1
src/Public/Layouts.ps1
src/Public/Pages.ps1

When defining a dynamic page with `-NoAuth`, elements/layouts will get the NoAuth value from the page's PageData variable - saving having to supply it.
Resolves #92

Get -NoAuth from PageData for dynamic pages

---

docs/Tutorials/Layouts/Accordion.md
docs/Tutorials/Outputs/Accordion.md
examples/accordion.ps1
src/Public/Layouts.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Public/styles/default-dark.css
src/Templates/Public/styles/default-light.css
src/Templates/Public/styles/default-terminal.css
src/Templates/Public/styles/default.css
src/Templates/Views/index.pode
src/Templates/Views/layouts/accordion.pode
src/Templates/Views/layouts/card.pode

Adds a new Accordion layout, which takes an arrow of "Bellows". The first bellow is displayed as expanded with the rest collapsed, and expanding another bellow will collapse all other bellows.
A bellow can contain or layouts/elements, and similar tabs they can be auto-cycled through.
The following renders an accordion with 3 bellows each containing an image:
```powershell
New-PodeWebAccordion -Bellows @(
New-PodeWebBellow -Name Bellow1 -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
New-PodeWebBellow -Name Bellow2 -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
New-PodeWebBellow -Name Bellow3 -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
)
```

Adds a new Accordion layout

---

docs/Tutorials/Outputs/Charts.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds a new `Sync-PodeWebChart` so you can refresh a chart as an output action.
Resolves #101
```powershell
New-PodeWebButton -Name 'Refresh Processes' -ScriptBlock {
Sync-PodeWebChart -Name 'Processes'
}
New-PodeWebChart -Name 'Processes' -Type Line -NoRefresh -ScriptBlock {
Get-Process |
Sort-Object -Property CPU -Descending |
Select-Object -First 15 |
ConvertTo-PodeWebChartData -LabelProperty ProcessName -DatasetProperty CPU
}
```

Add new Sync-PodeWebChart output action

---

examples/full.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/chart.pode

Adds support for specifying custom min/max values for the x/y axes on charts.
Resolves #102
```powershell
New-PodeWebCounterChart -Counter '\Processor(_Total)\% Processor Time' -MinY 0 -MaxY 100
```

Add min/max for x/y axes

---

examples/full.ps1
examples/tiles.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/chart.pode
src/Templates/Views/elements/table.pode
src/Templates/Views/elements/tile.pode

Adds support for a `-RefreshInterval` parameter for elements that have the `-AutoRefresh` switch. The default interval is 60s.
Support added to Charts, Tables, and Tiles - which means you could now have a tile that updates every 10s.
Resolves #105 
```powershell
New-PodeWebTile -Name Example -ScriptBlock { return ([datetime]::Now.ToString())} -AutoRefresh -RefreshInterval 5
```

Add support for RefreshInterval for AutoRefresh

---

docs/Tutorials/Basics.md
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/index.pode

Adds a new `-HideSidebar` switch to `Use-PodeWebTemplates`, which hides the sidebar by default on pages.
Resolves #125 
```powershell
Use-PodeWebTemplates -Title 'Example' -Theme Dark -HideSidebar 
```

Add a new -HideSidebar switch on Use-PodeWebTemplates

---

src/Public/Layouts.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/layouts/accordion.pode

Adds a new `-Mode` parameter to `New-PodeWebAccordian`. The valid modes are Normal, Collapsed, and Expanded - default is Normal.
If Collapsed is selected, the Accordian starts of with all Bellow collapsed. Or all expanded for Expanded.
Resolves #122
```powershell
New-PodeWebAccordion -Mode Collapsed -Bellows @(...)
```

Add -Mode parameter for Accordion, to toggle Normal, Collapsed, and Expanded

---

docs/Tutorials/Elements/Button.md
docs/Tutorials/Elements/Charts.md
docs/Tutorials/Elements/Form.md
docs/Tutorials/Elements/Table.md
docs/Tutorials/Elements/Tile.md
docs/Tutorials/Elements/Timer.md
docs/Tutorials/Layouts/Modal.md
docs/Tutorials/Layouts/Steps.md
docs/Tutorials/Pages.md
examples/dynamic-pages.ps1
src/Public/Elements.ps1
src/Public/Pages.ps1

Add `-ArgumentList` parameter to `Add-PodeWebPage`, and update docs for all elements/layouts to reference ArgumentList.
Resolves #137 
```powershell
Add-PodeWebPage -Name Example -ArgumentList 'value1', 2, $false -ScriptBlock {
param($value1, $value2, $value3)
}
```

Add -ArgumentList to Add-PodeWebPage, and update docs

---

docs/Tutorials/Outputs/Charts.md
docs/Tutorials/Outputs/Table.md
docs/Tutorials/Outputs/Textbox.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds new clear output actions for Charts, Tables, and Textboxes:
* `Clear-PodeWebChart`
* `Clear-PodeWebTable`
* `Clear-PodeWebTextbox`
Resolves #140 
```powershell
New-PodeWebButton -Name 'Clear Processes' -ScriptBlock {
Clear-PodeWebChart -Name 'Processes'
}
New-PodeWebChart -Name 'Processes' -Type Line -NoRefresh -ScriptBlock {
Get-Process |
Sort-Object -Property CPU -Descending |
Select-Object -First 15 |
ConvertTo-PodeWebChartData -LabelProperty ProcessName -DatasetProperty CPU
}
)
```

Adds new clear output actions for Charts, Tables, and Textboxes

---

docs/Tutorials/Outputs/Theme.md
docs/Tutorials/Themes.md
examples/full.ps1
src/Private/Helpers.ps1
src/Public/Outputs.ps1
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/index.pode
src/Templates/Views/login.pode

Adds new output actions for controlling the theme for a user: `Update-PodeWebTheme` and `Reset-PodeWebTheme`. The former take a `-Name` of a theme, and updates the users frontend to that theme. The latter resets a users frontend theme back to the default server's theme.
Resolves #115
```powershell
Use-PodeWebTemplates -Title Test -Theme Dark
New-PodeWebButton -Name 'Dark Theme' -Icon 'moon-new' -Colour Dark -ScriptBlock {
Update-PodeWebTheme -Name Dark
}
New-PodeWebButton -Name 'Light Theme' -Icon 'weather-sunny' -Colour Light -ScriptBlock {
Update-PodeWebTheme -Name Light
}
)
```

Adds output actions to control frontend theme for a user

---

docs/Tutorials/Elements/Select.md
docs/Tutorials/Outputs/Select.md
examples/inputs.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/select.pode

Add support for `-ScriptBlock` on `New-PodeWebSelect` so options can be built more dynamically. Also adds `Update/Clear/Sync-PodeWebSelect`, so you can update/clear/sync a select element's options.
Resolves #147 
```powershell
New-PodeWebContainer -Content @(
New-PodeWebButton -Name 'New Options' -ScriptBlock {
$options = @(foreach ($i in (1..10)) {
Get-Random -Minimum 1 -Maximum 10
})
$options | Update-PodeWebSelect -Name 'DynamicSelect'
}
New-PodeWebButton -Name 'Clear Options' -ScriptBlock {
Clear-PodeWebSelect -Name 'DynamicSelect'
}
New-PodeWebButton -Name 'Resync Options' -ScriptBlock {
Sync-PodeWebSelect -Name 'DynamicSelect'
}
New-PodeWebSelect -Name 'DynamicSelect' -Multiple -ScriptBlock {
return @(foreach ($i in (1..10)) {
Get-Random -Minimum 1 -Maximum 10
})
}
)
```

Add support for dynamic select elements

---

docs/Tutorials/Elements/Select.md
docs/Tutorials/Elements/Textbox.md
docs/Tutorials/Outputs/Textbox.md
examples/inputs.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/select.pode
src/Templates/Views/elements/textbox.pode

Adds a new `-Size` parameter to `New-PodeWebSelect` so when you make a multiple select you can customise the number of options shown - rather than the 4 default.
Resolves #149 
```powershell
New-PodeWebSelect -Name 'DynamicSelect' -Multiple -Size 6 -ScriptBlock { ... }
```

Add -Size parameter to New-PodeWebSelect for multiple selects

---

examples/catfacts.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds `-BackgroundColour` and `-Colour` to `Update-PodeWebTableRow`, allows you to change row colours. If no colour is specified, then the row is reset back to the theme's colour.
Resolves #151 
```powershell
Update-PodeWebTableRow -Name '<table-name>' -Index 0 -BackgroundColour Yellow -Colour Black
```

Allow Update-PodeWebTableRow to change row colour

---

docs/Getting-Started/Migrating/05-to-06.md
docs/Tutorials/Elements/Select.md
examples/inputs.ps1
src/Public/Elements.ps1
src/Templates/Views/elements/select.pode

Remove the `-NoChooseOption` and `-ChooseOptionValue` from `New-PodeWebSelect`. If people need a "choose an option", it can be defined using `-Options`, and if they don't, it's a simple case of not defining one.
Resolves #155
```powershell
New-PodeWebSelect -Name 'Role1' -Options @('Choose...', 'User', 'Admin', 'Operations')
```

Remove default 'choose option' option on select elements

---

docs/Tutorials/Elements/Checkbox.md
docs/Tutorials/Elements/FileUpload.md
docs/Tutorials/Elements/Radio.md
docs/Tutorials/Elements/Range.md
docs/Tutorials/Elements/Select.md
docs/Tutorials/Elements/Textbox.md
examples/input_events.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Public/styles/default.css
src/Templates/Views/elements/checkbox.pode
src/Templates/Views/elements/fileupload.pode
src/Templates/Views/elements/radio.pode
src/Templates/Views/elements/range.pode
src/Templates/Views/elements/select.pode
src/Templates/Views/elements/textbox.pode

A new `-NoForm` switch on most form elements could be used to display these elements more cleanly inline with other text elements.
Resolves #162 
```powershell
$select = New-PodeWebContainer -Content @(
New-PodeWebText -Value 'Please select a value: '
New-PodeWebSelect -Name 'Bellows' -NoForm -Options 'Bellow 1', 'Bellow 2', 'Bellow 3' |
Register-PodeWebEvent -Type Change -ScriptBlock {
Move-PodeWebAccordion -Name $WebEvent.Data['Bellows']
}
)
$acc1 = New-PodeWebAccordion -Bellows @(
New-PodeWebBellow -Name 'Bellow 1' -Icon 'information' -Content @(
New-PodeWebText -Value 'Some random text' -InParagraph
)
New-PodeWebBellow -Name 'Bellow 2' -Content @(
New-PodeWebText -Value 'Some random text' -InParagraph
)
New-PodeWebBellow -Name 'Bellow 3' -Content @(
New-PodeWebText -Value 'Some random …
```

Add new -NoForm switch on most form elements

---

docs/Tutorials/Outputs/Components.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds output functions for hiding/showing components, as well as setting/removing css style properties:
* `Hide-PodeWebComponent`
* `Show-PodeWebComponent`
* `Set-PodeWebComponentStyle`
* `Remove-PodeWebComponentStyle`
Each function can identify a component by its `-Id`, or by a `-Type` and `-Name` combo (for components that support a `-Name`). The `-Type` is like Table/Cell/Card/Textbox/Select/Bellow/etc.
Resolves #164 
To show a component:
```powershell
Show-PodeWebComponent -Type 'Card' -Name 'SomeCardName'
Show-PodeWebComponent -Id 'card_somename'
```
To set a css style property:
```powershell
Set-PodeWebComponentStyle -Type 'Textbox' -Name 'SomeTextboxName' -Property 'color' -Value 'red'
Set-PodeWebComponentStyle -Id 'textbox_somename' -Property 'color' -Value 'red'
```

Adds output functions for hiding/showing and updating css on components

---

docs/Tutorials/Elements/Charts.md
examples/charts.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/chart.pode

Adds more default colours for charts, and enables support to use custom colours via a new `-Colours` parameter on `New-PodeWebChart`.
Resolves #153 
For example, to render the below bar chart with reg/green bars, you could use:
```powershell
New-PodeWebContainer -Content @(
New-PodeWebChart -Name 'Top Processes' -Type Bar -AutoRefresh -Colours '#ff0000', '#00ff00' -ScriptBlock {
Get-Process |
Sort-Object -Property CPU -Descending |
Select-Object -First 10 |
ConvertTo-PodeWebChartData -LabelProperty ProcessName -DatasetProperty CPU, Handles
}
)
```

Add extra default chart colours, and support for customising them

---

examples/tables.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Add better support for initialising empty tables, where by you can use an empty scriptblock - or a scriptblock that returns nothing - and use the `-Columns` parameter with `Initialize-PodeWebTableColumn` to build the table's columns.
```powershell
New-PodeWebTable `
-Name 'Empty Table' `
-ScriptBlock {} `
-AsCard `
-Columns @(
Initialize-PodeWebTableColumn -Key 'Name'
Initialize-PodeWebTableColumn -Key 'ID'
Initialize-PodeWebTableColumn -Key 'WorkingSet' -Name 'Memory'
Initialize-PodeWebTableColumn -Key 'CPU'
)
```
Will render an empty table, with just the column headers showing.

Add better support for initialising empty tables

---

docs/Tutorials/Outputs/FileStream.md
examples/file-stream.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds the following output actions to better control FileStream elements:
* `Clear-PodeWebFileStream`
* `Start-PodeWebFileStream`
* `Stop-PodeWebFileStream`
* `Restart-PodeWebFileStream`
* `Update-PodeWebFileStream`
```powershell
New-PodeWebButton -Name 'Stop' -ScriptBlock {
Stop-PodeWebFileStream -Name 'Example'
}
New-PodeWebButton -Name 'Start' -ScriptBlock {
Start-PodeWebFileStream -Name 'Example'
}
New-PodeWebButton -Name 'Restart' -ScriptBlock {
Restart-PodeWebFileStream -Name 'Example'
}
New-PodeWebButton -Name 'Clear' -ScriptBlock {
Clear-PodeWebFileStream -Name 'Example'
}
New-PodeWebButton -Name 'Update 1' -ScriptBlock {
Update-PodeWebFileStream -Name 'Example' -Url '/logs/error.log'
}
New-PodeWebButton -Name 'Update 2' -ScriptBlock {
Update-PodeWebFileStream -Name 'Example' -Url …
```

Add FileStream output actions

---

package.json

Bump the version of bootstrap from v4.6.0 to v4.6.1

Bump bootstrap to v4.6.1

---

docs/Tutorials/Pages.md
src/Public/Pages.ps1
src/Templates/Views/index.pode

Adds a new `-Hide` switch to `Add-PodeWebPage` and `Add-PodeWebPageLink`, which will stop the page appearing in the sidebar.
This also fixes the "count" of pages next to Groups in the sidebar. Also, if all pages in a group are set to "hide" or aren't accessible by auth, then the group is hidden as well.
Resolves #207 
```powershell
Add-PodeWebPage -Name Charts -Hide -Layouts @(
New-PodeWebCard -Content @(
New-PodeWebCounterChart -Counter '\Processor(_Total)\% Processor Time'
)
)
```

Add -Hide switch to stop pages appearing in sidebar

---

src/Public/Elements.ps1
src/Templates/Views/elements/checkbox.pode
src/Templates/Views/elements/credential.pode
src/Templates/Views/elements/datetime.pode
src/Templates/Views/elements/fileupload.pode
src/Templates/Views/elements/minmax.pode
src/Templates/Views/elements/radio.pode
src/Templates/Views/elements/range.pode
src/Templates/Views/elements/select.pode
src/Templates/Views/elements/textbox.pode

Each of the form elements, like textboxes/selects/etc, have had a new `-Required` switch added. When supplied, the HTML `required` property will be added to the element, requiring them to be entered.
Resolves #208 
```powershell
New-PodeWebTextbox -Required
```

Add -Required switch to form elements

---

docs/Tutorials/Elements/Text.md
examples/full.ps1
src/Public/Elements.ps1
src/Templates/Public/styles/default.css
src/Templates/Views/elements/text.pode

Adds a new `-Pronunciation` parameter onto `New-PodeWebText`, which displays small text above words/phrases showing their pronuncation.
```powershell
New-PodeWebText -Value '漢' -Pronunciation 'ㄏㄢˋ'
```

Add ruby pronunciation support on text

---

docs/Tutorials/Elements/Checkbox.md
docs/Tutorials/Elements/Credentials.md
docs/Tutorials/Elements/DateTime.md
docs/Tutorials/Elements/FileUpload.md
docs/Tutorials/Elements/MinMax.md
docs/Tutorials/Elements/Radio.md
docs/Tutorials/Elements/Range.md
docs/Tutorials/Elements/Select.md
docs/Tutorials/Elements/Textbox.md
docs/Tutorials/Outputs/Select.md
src/Private/Helpers.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/checkbox.pode
src/Templates/Views/elements/credential.pode
src/Templates/Views/elements/datetime.pode
src/Templates/Views/elements/fileupload.pode
src/Templates/Views/elements/minmax.pode
src/Templates/Views/elements/radio.pode
src/Templates/Views/elements/range.pode
src/Templates/Views/elements/select.pode
src/Templates/Views/elements/textbox.pode

Adds the new `-DisplayName` parameter to each Form element: textbox, checkbox, radio, select, file-upload, select, range, credentials, datetime, and minmax.
Also adds the new `-DisplayOptions` parameter to each of: checkbox, radio, and select.
These override the values displayed on the frontend, instead of using `-Name` and `-Options`. They purely visual, and the original values are still returned back to the server on form submission.
Resolves #161 
```powershell
New-PodeWebForm -Name 'New User' -ScriptBlock {
$name = $WebEvent.Data.Name
$role = $WebEvent.Data.Role
} -Content @(
New-PodeWebTextbox -Name 'Name' -DisplayName 'Nom'
New-PodeWebSelect `
-Name 'Role' `
-DisplayName 'Rôle' `
-Options @('Developer', 'Admin', 'Operations') `
-DisplayOptions @('Développeur', 'Administrateur', …
```

Add DisplayName and DisplayOptions parameters for form elements

---

docs/Tutorials/Elements/Audio.md
docs/Tutorials/Elements/Charts.md
docs/Tutorials/Elements/Image.md
docs/Tutorials/Elements/Table.md
docs/Tutorials/Elements/Textbox.md
docs/Tutorials/Elements/Video.md
docs/Tutorials/Sizes.md
src/Private/Helpers.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/chart.pode
src/Templates/Views/elements/image.pode
src/Templates/Views/elements/textbox.pode

Enable the new raw CSS size logic to work for Textboxes, Charts, Images, and Table Columns.
If you wanted to add a image of 100px by 100px you could do:
```powershell
New-PodeWebImage -Source '/url/to/image.png' -Width 100 -Height 100
```
and Pode.Web will append the default `px` unit. If instead you wanted a image at 25% and 10em:
```powershell
New-PodeWebImage -Source '/url/to/image.png' -Width '25%' -Height '10em'
```

Allow textbox, chart, image, table-cols to use CSS sizes

---

docs/Tutorials/Elements/Form.md
docs/Tutorials/Layouts/Modal.md
src/Public/Elements.ps1
src/Public/Layouts.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/form.pode
src/Templates/Views/layouts/modal.pode

Adds two new `-Method` and `-Action` parameters onto `New-PodeWebForm` and `New-PodeWebModal`. This allows the overriding of the default method/action properties for forms.
Resolves #214
```powershell
New-PodeWebForm -Name 'Example' -Method Get -Action 'https://example.com/some/url' -ScriptBlock {} -Content @()
```

Add method/action parameters for forms

---

docs/Tutorials/Elements/Form.md
examples/inputs.ps1
src/Public/Elements.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/form.pode

Adds a `-ShowReset` switch onto `New-PodeWebForm`, and if supplied an optional reset button will be rendered for the form. Clicking it will reset all form inputs to their defaults.
Resolves #211

Add optional reset button for forms

---

docs/Tutorials/Elements/Credentials.md
docs/Tutorials/Elements/DateTime.md
docs/Tutorials/Elements/MinMax.md
src/Public/Elements.ps1
src/Templates/Views/elements/credential.pode
src/Templates/Views/elements/datetime.pode
src/Templates/Views/elements/minmax.pode

Adds new `-Type` parameter for DateTime, Credentials and MinMax to allow selecting which fields are displayed.
Resolves #230 
```powershell
New-PodeWebDateTime -Name 'Example' -Type Date, Time
New-PodeWebCredential -Name 'Example' -Type Username, Password
New-PodeWebMinMax -Name 'Example' -Type Min, Max
```

Add -Type param to datetime, creds, and minmax

---

examples/full.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/code.pode
src/Templates/Views/elements/codeblock.pode

Fixes a bug with `Update-PodeWebText` where it wouldn't update code/block elements.
Resolves #233

Fix update-text to work with code blocks

---

docs/Tutorials/Elements/FileUpload.md
examples/upload.ps1
src/Public/Elements.ps1
src/Templates/Views/elements/fileupload.pode

Adds a new `-Accept` parameter onto `New-PodeWebFileUpload`, to control what the file-upload dialog accepts. When not supplied, the default is everything (`*/*`).
Resolves #235 
```powershell
New-PodeWebFileUpload -Name 'File' -Accept '.png', 'audio/*'
```

Add -Accept support for FileUpload

---

src/Public/Outputs.ps1

Add `-Force` switch to `Update-PodeWebTable`, to skip the Paginate check when updating tables from another element.
Resolves #238

Add -Force to Update-PodeWebTable

---

docs/Tutorials/Events.md
docs/Tutorials/Pages.md
examples/full.ps1
src/Private/Events.ps1
src/Private/Helpers.ps1
src/Public/Events.ps1
src/Public/Pages.ps1
src/Public/Utilities.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/index.pode
src/Templates/Views/login.pode

Add page events for Load, Unload and BeforeUnload for custom pages (`Add-PodeWebPage`), plus Home/Login pages (`Set-PodeWebHomePage` / `Set-PodeWebLoginPage`).
Resolves #234 
Login:
```powershell
Set-PodeWebLoginPage -Authentication Example  -PassThru |
Register-PodeWebPageEvent -Type Load, Unload, BeforeUnload -NoAuth -ScriptBlock {
Show-PodeWebToast -Message "Login page $($EventType)!"
}
```
Home:
```powershell
Set-PodeWebHomePage -PassThru |
Register-PodeWebPageEvent -Type Load, Unload, BeforeUnload -ScriptBlock {
Show-PodeWebToast -Message "Home page $($EventType)!"
}
```
Custom:
```powershell
Add-PodeWebPage -Name Charts -PassThru |
Register-PodeWebPageEvent -Type Load, Unload, BeforeUnload -ScriptBlock {
Show-PodeWebToast -Message "Page $($EventType)!"
}
```

Add page events for Load, Unload and BeforeUnload

---

docs/Tutorials/Elements/Table.md
examples/tables.ps1
src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/table.pode

Applies a few fixes for tables, and also a couple extra enhancements:
* Bug: `Initialize-PodeWebColumn` wasn't being respected on manual calls to `Update-PodeWebTable`
* Bug: If you tried to show "0" or empty values in tables, nothing would be displayed - not even "0"
* New: `-Compact` on `New-PodeWebTable` to remove padding on rows
* New: `-Default` on `Initialize-PodeWebColumn`, this will be used in a column if the row value to be used is null

A few minor fixes/enhancements for tables/columns

---

.build.ps1
docs/Tutorials/Outputs/CodeEditor.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/code-editor.pode

Adds `Update-PodeWebCodeEditor` to enable updating the value and/or language of a code-editor. Also adds `Clear-PodeWebCodeEditor` to clear the value of a code-editor.
Resolves #210 
```powershell
New-PodeWebCodeEditor -Language PowerShell -Name 'Code Editor' -Value "Write-Host 'hi!'"
New-PodeWebButton -Name 'Clear Editor' -ScriptBlock {
Clear-PodeWebCodeEditor -Name 'Code Editor'
}
)
```
and
```powershell
New-PodeWebCodeEditor -Language PowerShell -Name 'Code Editor'
New-PodeWebButton -Name 'Update Editor' -ScriptBlock {
Update-PodeWebCodeEditor -Name 'Code Editor' -Value '<optional-value>' -Language '<optional-language>'
}
)
```

Add update/clear output actions for code-editors

---

docs/Tutorials/Outputs/Checkbox.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds `Enable-PodeWebCheckbox` and `Disable-PodeWebCheckbox` output actions. Also adds a `-State` parameter onto `Update-PodeWebCheckbox` to toggle disabled/enabled (the default is "unchanged").
* Disable
```powershell
New-PodeWebCheckbox -Name 'Enable' -AsSwitch
New-PodeWebButton -Name 'Disable Checkbox' -ScriptBlock {
Disable-PodeWebCheckbox -Name 'Enable'
}
)
```
* Enable
```powershell
New-PodeWebCheckbox -Name 'Disabled' -AsSwitch -Disabled
New-PodeWebButton -Name 'Enable Checkbox' -ScriptBlock {
Enable-PodeWebCheckbox -Name 'Disabled'
}
)
```

Add enable/disable checkbox output actions

---

docs/Tutorials/Outputs/IFrame.md
examples/iframe.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds a new `Update-PodeWebIFrame` output action, to update an IFrame's URL and/or Title
```powershell
$con1 = New-PodeWebContainer -Content @(
1..3 |  ForEach-Object {
New-PodeWebButton -Name "Page$_" -ScriptBlock {
Update-PodeWebIFrame -Name 'IFrame' -Url "/pages/$($ElementData.Name)"
}
}
)
$con2 = New-PodeWebContainer -Content @(
New-PodeWebIFrame -Name 'IFrame' -Url '/pages/Page1'
)
Add-PodeWebPage -Name 'Example' -Layouts $con1, $con2
1..3 |  ForEach-Object {
Add-PodeWebPage -Name "Page$_" -Hide -Layouts @(
New-PodeWebContainer -Content @(
New-PodeWebText -Value "Page$_!"
)
)
}
```

Add Update-PodeWebIFrame output action

---

docs/Tutorials/Pages.md
examples/full.ps1
src/Public/Pages.ps1
src/Templates/Views/index.pode

Add a new `-NoSidebar` switch to `Add-PodeWebPage`, which will hide the sidebar on the page - useful for dashboards.
```powershell
Add-PodeWebPage -Name Charts -NoSidebar -Layouts @(
New-PodeWebCard -Content @(
New-PodeWebCounterChart -Counter '\Processor(_Total)\% Processor Time'
)
)
```

Add -NoSidebar switch for pages, to hide sidebar per page

---

src/Templates/Public/styles/default-light.css

Fix icon-only button colour on light theme.
Resolves #254

Fix light theme icon-only colour for buttons

---

src/Templates/Public/scripts/default.js
src/Templates/Views/elements/button.pode

Fix the hover value displayed over a button to be the DisplayName, not the Name.

Fix the hover title on IconOnly buttons to show DisplayName

---

docs/Tutorials/Outputs/Form.md
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js

Adds a new `Submit-PodeWebForm` output action, so that forms can be submitted dynamically; such as from another button, or via an event (like page load, etc.).
Resolves #273 
```powershell
New-PodeWebCard -Content @(
New-PodeWebForm -Name 'Example' -ScriptBlock {} -Content @(
New-PodeWebTextbox -Name 'Name'
New-PodeWebTextbox -Name 'Password' -Type Password -PrependIcon Lock
New-PodeWebCheckbox -Name 'Checkboxes' -Options @('Terms', 'Privacy') -AsSwitch
New-PodeWebSelect -Name 'Role' -Options @('User', 'Admin', 'Operations') -Multiple
)
)
New-PodeWebButton -Name 'Submit Form' -ScriptBlock {
Submit-PodeWebForm -Name 'Example'
}
)
```

Add Submit-WebPodeForm output action

---

examples/basic.ps1
src/Public/Elements.ps1
src/Templates/Views/elements/form.pode

Adds two new `-SubmitText` and `-ResetText` parameters on `New-PodeWebForm`, so their values can be customised.
Resolves #274 
```powershell
New-PodeWebForm -Name 'Search' -ShowReset -SubmitText 'Search' -ResetText 'Clear' -AsCard -ScriptBlock {
Get-Process -Name $WebEvent.Data.Name -ErrorAction Ignore | Select-Object Name, ID, WorkingSet, CPU | Out-PodeWebTextbox -Multiline -Preformat -AsJson
} -Content @(
New-PodeWebTextbox -Name 'Name'
)
```

Add Submit/ResetText parameters for Form buttons

---

docs/Tutorials/Layouts/Grid.md
src/Private/Helpers.ps1
src/Public/Layouts.ps1

Allows the `-Width` on `New-PodeWebCell` to optionally also be supplied as a percentage. Also documents why the numbers are 1-12.
Resolves #284 
```powershell
New-PodeWebGrid -Cells @(
New-PodeWebCell -Width 6 -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
New-PodeWebCell -Width '25%' -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
New-PodeWebCell -Width 3 -Content @(
New-PodeWebImage -Source '/pode.web/images/icon.png' -Alignment Center
)
)
```

Allow for cell width to also be a percentage

---

docs/Tutorials/Pages.md
examples/full_iis.ps1
examples/web.config
src/Public/Pages.ps1
src/Public/Utilities.ps1
src/Templates/Views/index.pode

Adds a new `Set-PodeWebAuth` function so authentication methods that don't need a login page can be set - such as IIS, Basic, Digest, etc.
For the case of each, Pode.Web checks if theirs a session available and authenticated, and this is used to display the current user.
Similar to `Set-PodeWebLoginPage`, this function also wires up the authentication on all pages as well. The logout button is hidden, as there's no need since authentication is dealt with elsewhere.
Resolves #129 
The below will configure Pode.Web pages to use IIS authentication.
```powershell
Enable-PodeSessionMiddleware -Duration 120 -Extend
Add-PodeAuthIIS -Name Example
Set-PodeWebAuth -Authentication Example
```

Add Set-PodeWebAuth for login methods like IIS

---

src/Templates/Public/scripts/default.js
src/Templates/Public/styles/default.css
src/Templates/Views/elements/table.pode

This cleans up the table pagination controls, so they're a little easier to look at and use. The "..." has gone, and the first/last numbers have been replaced with first/last chevron buttons instead.
When you click for another page, the table now clears and show a spinner to show that it's actually doing something.
There's now a textbox next to the paging control, which allows altering the number of items that show in the table! 🚀

Clean up table paging control, show spinner when reloading, and add paging size control

---

src/Public/Elements.ps1
src/Public/Outputs.ps1
src/Templates/Public/scripts/default.js
src/Templates/Views/elements/select.pode

This adds support for selecting multiple options of a multi select element during creation/update. Therefore parameter `-SelectedValue` was changed to accept a list of values for:
- `New-PodeWebSelect`
- `Update-PodeWebSelect`
Creating a non-multiple select element with multiple selected values will create an exception.
Updating a non-multiple select element with multiple selected values will select only the first one.
#304 
- New select with multiple preselected values:
```powershell
New-PodeWebCard -Content @(
New-PodeWebForm -Name 'Example Form' -ScriptBlock {
$WebEvent.Data | Out-Default
} -Content @(
New-PodeWebSelect -Name 'Role2' `
-Options @('User', 'Admin', 'Operations') `
-Multiple `
-SelectedValue @('User', 'Operations')
)
)
```
- Update select with multiple selected values …

Add support for multiple pre-selected values

---

src/Private/Helpers.ps1

Fix for choosing the module path to use, when multiple versions of Pode.Web happen to be imported at the same time. The latest version available will be chosen - matching similar logic in Pode.
Resolves #299

Choose latest module version when multiple are imported

---

src/Public/Elements.ps1

Add allow empty string attribute to the Value parameter.
#335 
As we can see, page loads happily, HTML looks happy as well, and this prevents unexpected when incoming value is in fact an empty string.

Allow empty string for hidden value

---

src/Private/Helpers.ps1
src/Templates/Views/index.pode

Fixes a bug where if the `-Group` value for `Add-PodeWebPage` contained a space, the section wouldn't expand and pages wouldn't load.
This fix keeps the space in place on the page visually, but replaces the space internally with an underscore to preserve HTML `id`'s.
Resolves #255 
Resolves #323

Fix group names with spaces

---

src/Private/Helpers.ps1
src/Templates/Views/index.pode

Allows special characters to be used in group/page names, without breaking JS selectors.
Characters:
```
!"#$%&'()*+,./:;<=>?@[\]^`{|}~
```
Resolves #369

Escapes special characters in group/page names

---

examples/full.ps1
examples/inputs.ps1
src/Pode.Web.psd1
src/Public/Utilities.ps1

Use RequiredModules to make sure Pode is loaded, instead of using custom logic to do the same thing.
Resolves #333

Use RequiredModules instead to make sure Pode is loaded

---

.build.ps1
.github/workflows/ci.yml
Dockerfile
alpine.dockerfile
arm32.dockerfile
docs/Getting-Started/Installation.md
docs/Hosting/Docker.md

Bumps the dockerfiles to use Pode v2.7.2.
Resolves #350

Bump dockerfiles to use Pode v2.7.2

---

src/Templates/Public/scripts/default.js
src/Templates/Views/index.pode

Resolve https://github.com/Badgerati/Pode.Web/issues/384
1. Pages display name where encoded in "Pages.ps1" and again in "index.pode". I remove the "index.pode"
2. Buttons and validation display name are encoded in "Elements.ps1" and "default.js". I added a `decodeHTML` between the encodings as in the other elements there.

FixDecoding

---

src/Templates/Views/elements/textbox.pode

Fix Output with `New-PodeWebTextbox -NoForm` part of https://github.com/Badgerati/Pode.Web/issues/390
Now it is possible to create wide `New-PodeWebTextbox -NoForm`
Before
After
```powershell
Add-PodeWebPage -Name Services -DisplayName 'Test' -Icon 'cogs' -ScriptBlock {
New-PodeWebTextbox -Name 'Name1' -Multiline -DynamicLabel
New-PodeWebTextbox -Name 'Name2' -Multiline -NoForm
New-PodeWebTextbox -Name 'Name1' -Multiline -DynamicLabel -Width 50
New-PodeWebTextbox -Name 'Name2' -Multiline -NoForm -Width 50
New-PodeWebForm -Name 'Search' -Content @(
New-PodeWebTextbox -Name 'Name'
) -ScriptBlock {
Start-Sleep 3
Out-PodeWebValidation -Name 'Name' -Message 'Username m"ust be 4+ chars'
}
New-PodeWebButton -Name 'Search' -Icon 'magnify' -ScriptBlock {
Out-PodeWebTextbox -Value ''
}
}
```

TextBoxNoFormWidth

---

.gitignore
src/Public/Outputs.ps1

Fixes a new-line issue prevents `Update-PodeWebTextbox` from working with Date input types.
Resolves #413 
```powershell
Update-PodeWebTextbox -Name 'Date1' -Value '2023-02-08'
```

Fix Update-PodeWebTextbox to work with date types

---

src/Templates/Public/scripts/default.js

Fixes an issue where pressing the enter key in a multline text input, in a modal, submitted the modal.
Resolves #380

Fix pressing enter key in textarea in modal

---

Dockerfile
alpine.dockerfile
arm32.dockerfile
docs/Getting-Started/Installation.md
docs/Hosting/Docker.md

Bump Pode to v2.8.0 in the Dockerfiles.
Resolves #418

Bump pode to 2.8.0 in dockerfiles

---

docs/release-notes.md
src/Public/Pages.ps1

Temporary fix for the back button on pages, to not show when there is no query string
Resolves #430

Temp fix for showing the back button
